### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by maflister** [icbi-lab/nextNEOpi#15]
Why is patch used in the pipeline? Would it not be easier for your team to provide a patched file with each release of the pipeline. It would remove a dependency that many users wouldn't normally have installed.

Thanks

**Comment by riederd** [comment]
Hi,
thanks for your interest in nextNEOpi.

Patch is used to apply specific changes to `NeoAg_immunogenicity_predicition_GBM.R` which is, due to licence restrictions, not bundled or distributed with nextNEOpi. It is downloaded on runtime from GitHub.

However, we seem to have forgotten to add the patch program to the singularity image, which we will do for our next release.

Thanks
