### ISSUE TITLE
Error executing process > 'make_uBAM (sample1 : normal_DNA)'

### ISSUE THREAD

**Issue by rezakj** [icbi-lab/nextNEOpi#23]
Hi, 

I am getting the following error (make_uBAM). I attached the log file. 

Thanks for the help and. the amazing pipeline. 

[slurm-21392618.out.txt](https://github.com/icbi-lab/nextNEOpi/files/11253076/slurm-21392618.out.txt)

**Comment by riederd** [comment]
Hi, thanks for your interest in `nextNEOpi`

It seems that your slurm scheduler has killed the job because it was running out of memory:
```
slurmstepd-fn2-0002: error: *** JOB 21392618 ON fn2-0002 CANCELLED AT 2023-04-17T11:26:50 ***
slurmstepd-fn2-0002: error: Detected 1 oom-kill event(s) in StepId=21392618.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
You might need to reserve more memory, you can do so in `conf/process.config`

https://github.com/icbi-lab/nextNEOpi/blob/aac260dbd5da701d22a09846045f3f42981cd4a1/conf/process.config#L28

add:
`memory '64 GB'`

**Comment by rezakj** [comment]
Thank you so much!
